### ISSUE TITLE
Collaboration offer?

### ISSUE THREAD

**Issue by lolouk44** [wiecosystem/Bluetooth#1]
Not so much an issue, more a request of potential help/collaboration.
I have a Xiaomi Scale v2. I currently use a [script ](https://github.com/lolouk44/xiaomi_mi_scale) to retrieve the scales measures, but it does not include additional body measurements that you have in your github.
I'm an amateur programmer but would love to re-use you code to improve mine, and potentially create a component for [home-assistant](https://home-assistant.io) as there is quite some demand for a component for this scale.
Would this collaboration be of interest to you?

**Comment by prototux** [comment]
Well, you can use the code in this project, it's under the Apache2 licence (which i've just found is missing, i need to fix that). Beside that, i don't really understand what kind of collaboration you offer, as it isn't planned to make a hass component, but to make a agnostic SDK so any project (including my own HA system which isn't related to hass) can use it freely, so you can just use the code here in your component if you want to, that's the goal of this project.
