### ISSUE TITLE
huami.health.scale2

### ISSUE THREAD

**Issue by freenetwork** [wiecosystem/Bluetooth#2]
Please tell me how to get vi gatttool weight history?

**Comment by prototux** [comment]
I don't think you can use gatttool with xiaomi's devices to query data (such as the weight history), unfortunately, as these use a proprietary authentication system that would be quite difficult to do with gatttool.

You can however get readings when somebody goes on the scale, as it's sent using ble advertisements and it doesn't require any auth (which is really not secure, sadly).
