### ISSUE TITLE
Are the Mi Body Composition Scale, original and "2" both supported?

### ISSUE THREAD

**Issue by drewster99** [wiecosystem/Bluetooth#5]
Hi, I see there are two Huami body compositions Cales -- "Mi Body Composition Scale" and "Mi Body Composition Scale 2".  Do you know if both are supported?

**Comment by prototux** [comment]
I think they are kinda the same, but i don't own a composition scale 2, so, i can't guarantee that.
I think the easiest way to find out would be to get a frame from the scale 2 and see if the data matches between the python code and mi fit.

**Comment by drewster99** [comment]
Oh I see.  I’m just trying to figure out a device I can buy that has a known protocol I can program to.

Any recommendations?  Presumably the original Mi, I guess?

Thanks a lot!

On Aug 26, 2020, at 1:39 PM, Jason F. <notifications@github.com> wrote:

﻿
I think they are kinda the same, but i don't own a composition scale 2, so, i can't guarantee that.
I think the easiest way to find out would be to get a frame from the scale 2 and see if the data matches between the python code and mi fit.

**Comment by prototux** [comment]
The mi body composition scale is completly reverse engineered, the mi scale (without the body composition part, so the first even mi scale) is completly reverse engineered as far as i know, for the rest i don't know yet, so it's really up to what reverse engineering you're willing to do, if you feel adventurous you can get one of the newest ones, else you can probably stay with the first mi scale or mi body composition scale :)

**Comment by drewster99** [comment]
FYI, the same decoding logic worked with the Mi Fit Body Composition 2.

**Comment by zibous** [comment]
I have a Mi Body Composition Scale 2 (XMTZC05HM) and get wrong results when calculating, 
especially for Visceral Fat and Body Fat. 

![Bildschirmfoto 2020-09-03 um 18 22 15](https://user-images.githubusercontent.com/30198737/92141249-7bad5300-ee12-11ea-95e1-58caeae158e6.png)


If I query these values from other scales, then they are correct.

see: https://github.com/lolouk44/hassio-addons/issues/14

**Comment by prototux** [comment]
So, they use the same BLE format, but their calculations are different, apparently (the calculations on the v1 are made by a native library, from the OEM of the microcontroller that is used in the scale, not from xiaomi/huami)

For now, my guess would be that they either used a completly different microcontroller OEM, hence a different library/way to calculate, ot that they used a different microcontroller from the same OEM with slightly different calculations.
