### ISSUE TITLE
How to use mibcs_app.py ?

### ISSUE THREAD

**Issue by RobertWojtowicz** [wiecosystem/Bluetooth#8]
I would like to read data from a scale, but using the mibcs_app.py script I get an error: No module named 'body'

Could I ask for your help?

Best Regards,
Robert

**Comment by prototux** [comment]
it should be fixed, body is the older file for body_metrics.py, before i've added the body score and moved the scales to it's own file.

the mibcs_app.py is just a small test app for the body_*.py files, if you want to make your own app using these, you don't need mibcs_test.py and mibcs_app.py :)

**Comment by RobertWojtowicz** [comment]
Hi, @prototux

Just trying to get impedance, weight and date/time of weighing. I would like to add direct bluetooth read functionality to my project: https://github.com/RobertWojtowicz/miscale2garmin

I'm not good at programming, the easiest thing to do would be similar to here: http://www.d0wn.com/using-bash-and-gatttool-to-get-readings-from-xiaomi-mijia-lywsd03mmc-temperature-humidity-sensor/

EDIT, it works !, maybe it can be simpler is it possible to do it with a gatttol ?
```
#!/usr/bin/python
from bluepy import btle

class miScale(btle.DefaultDelegate):
    def __init__(self):
        btle.DefaultDelegate.__init__(self)
        self.address = "c8:b2:1e:c9:66:83"

    def handleDiscovery(self, dev, isNewDev, isNewData):
        if dev.addr == self.address:
            for (adType, desc, value) in dev.getScanData():
                if adType == 22:
                    data = bytes.fromhex(value[4:])
                    print("\t Date = {}/{}/{} {}:{}:{}".format(int(data[5]), int(data[4]), int((data[3] << 8) | data[2]), int(data[6]), int(data[7]), int(data[8])))
                    impedance = ((data[10] & 0xFF) << 8) | (data[9] & 0xFF)
                    weight = (((data[12] & 0xFF) << 8) | (data[11] & 0xFF)) / 200.0
                    print("\t impedance is {}".format(impedance))
                    print("\t weight is {}".format(weight))

    def run(self):
        scanner = btle.Scanner()
        scanner.withDelegate(self)
        scanner.start()
        scanner.process(1)
        scanner.stop()

scale = miScale()
scale.run()
```

BR,
Robert

**Comment by prototux** [comment]
It is probably possible to do it with gatttool but it will be very inefficient, especially since you would need to run python to transform the impedance to the health data anyway.

What you would need if you want to port it to another platform, is to capture BLE advertisement frames, filter with your MAC address and with the advertisement frame type 22, then parse the data from it, and then calculate the body metrics from the impedance (and the other data that doesn't comes from the scale).
